import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/header/Navigation';

const mont = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={mont.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
