import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import SSNavigation from '@/components/header/Navigation';
import { initializeApp } from 'firebase/app';
import 'dotenv/config';
import { getFirestore } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';

const mont = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const firebaseConfig = {
  apiKey: `${process.env.FIREBASE_API_KEY}`,
  authDomain: 'ev-cath-tg-bot.firebaseapp.com',
  databaseURL:
    'https://ev-cath-tg-bot-default-rtdb.europe-west1.firebasedatabase.app',
  projectId: 'ev-cath-tg-bot',
  storageBucket: 'ev-cath-tg-bot.appspot.com',
  messagingSenderId: '648508453377',
  appId: '1:648508453377:web:b2fa7ba7beef40893fc600',
};

const app = initializeApp(firebaseConfig);
export const db = getFirestore(app);
export const st = getStorage(app);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ru'>
      <body className={mont.className}>
        <SSNavigation />
        {children}
      </body>
    </html>
  );
}
